#include "Agenda.h"




Contact &Agenda::getContactByName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A4F begin
{
}
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Prieten Agenda::getPrieteni()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A51 begin
{
}
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A51 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Agenda::deleteContact(String name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A53 begin
{
    
}
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Agenda::addContact(String name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A56 begin
{
    
}
// section -84-17-0-1-26dee9f4:17989e91197:-8000:0000000000000A56 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
